"""init db 1a asaaaad

Revision ID: 1269beb85698
Revises: 1aa7499542d7
Create Date: 2023-04-27 14:59:03.943981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1269beb85698'
down_revision = '1aa7499542d7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
