"""agregando tabla user_token

Revision ID: 54f3e03f051e
Revises: 1269beb85698
Create Date: 2023-04-27 15:32:56.412370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54f3e03f051e'
down_revision = '1269beb85698'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token_user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token', sa.Text(), nullable=True),
    sa.Column('caducidad', sa.DateTime(), nullable=True),
    sa.Column('user_cedula', sa.String(length=11), nullable=True),
    sa.ForeignKeyConstraint(['user_cedula'], ['user.cedula'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_token_user_id'), 'token_user', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_token_user_id'), table_name='token_user')
    op.drop_table('token_user')
    # ### end Alembic commands ###
