"""init db

Revision ID: 721290c4b626
Revises: 
Create Date: 2023-04-27 14:05:08.636888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '721290c4b626'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
