"""init db 1a a

Revision ID: da00cb63846e
Revises: 721290c4b626
Create Date: 2023-04-27 14:53:11.821930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da00cb63846e'
down_revision = '721290c4b626'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
